version: 2.1
jobs:
  build:
    docker:
      - image: node:10.15.3-alpine

    steps:
      - setup_remote_docker

      - checkout

      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - node-modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}

      - run: npx roboter
